### ISSUE TITLE
Clock blinking in and out

### ISSUE THREAD

**Issue by whippc** [concerto/concerto#1470] opened 2018-01-18 21:05 UTC
It seems the clock field wants to blink in and out like its refreshing every 5 seconds. I have tried setting the transition but it doesnt help.

**Comment by timparenti** [comment] 2018-01-21 20:13
This sounds as though it may be a duplicate of #1451.

**Comment by mfrederickson** [comment] 2018-03-14 20:05
Thanks @timparenti.  This is a duplicate. Closing.  @whippc I'd recommend using Chrome if you can-- doesn't appear to happen with it.

**Closed by mfrederickson** 2018-03-14 20:05 UTC
Labels: 2.x
