### ISSUE TITLE
Use Houndci

### ISSUE THREAD

**Issue by acrogenesis** [concerto/concerto#1191] opened 2015-03-16 23:48 UTC
`Your code, always in style.
Hound comments on style violations in GitHub pull requests, allowing you and your team to better review and maintain a clean codebase.`

The codebase mixes different coding styles it would be nice to standardize this.
https://houndci.com - It's free for open source

**Comment by kench** [comment] 2015-03-17 15:02
> The codebase mixes different coding styles it would be nice to standardize this.

Is there anything specific you'd like to point out?

**Comment by acrogenesis** [comment] 2015-03-17 17:13
There's a lot of use of redundant self on models for example on `dynamic_content.rb`
![screen shot 2015-03-17 at 11 08 23 am](https://cloud.githubusercontent.com/assets/1312687/6693031/fa9b92fc-cc95-11e4-867b-19ac8aa9319f.png)

There's no clear preference between single-quotes and double-quotes.
Using parenthesis on method calls without arguments.
The codebase mixes and has a lot of Ruby 1.8 Hash syntax and Ruby 1.9. ( `:something => :whatever`, `something: :whatever`

This is all superficial, while not critical is a nice to have.

I have installed [Rubocop](https://github.com/bbatsov/rubocop) to help me keep the same syntax on all my codebase of all my projects. (It's one of the tools houndci uses)

**Comment by zr2d2** [comment] 2015-03-17 18:52
I think different developers on this project have been using their own coding style without a style guide, and that results in inconsistencies. I'd say things like redundant use of self keywords are more important than having extra parenthesis, though both are important to the readability of the code base. @augustf just submitted #1192 in order to remove hash syntax, though the colon syntax isn't a universal replacement, (in particular keys that aren't symbols). I think Concerto would benefit from a better use of Ruby syntax, and better coding standards

**Comment by kench** [comment] 2015-03-18 01:36
Personally, I like coding standards and I'm happy this was brought up.  If we are to introduce a coding standard, there should be agreement about what should be enforced.  I'm for any solution that doesn't introduce an undue amount of friction to the development process.  HoundCI looks like a good idea.

(I heavily dislike GitHub's style of using merge commits when merging pull requests and I prefer "squashing" commits in a pull request, but that's a discussion for another time.)

**Comment by zr2d2** [comment] 2015-03-21 20:38
I don't see a problem with a commit that says "merged pull request #n from forked_repo", it allows me to go to the PR and see the diff for the entire PR. And having individual commits allows me to review atomic changes, without reviewing related changes in a PR. For instance, using TDD i would put code required to pass a test into a single commit. maybe part of the style guide is about creating meaningful commits and messages

**Comment by kench** [comment] 2015-03-22 08:44
> Part of the style guide is about creating meaningful commits and messages

You've nailed the root cause of my annoyance.  :)

**Comment by augustf** [comment] 2015-03-24 22:22
Going back to the original discussion, I'm not sure this will be very much help for us, as the code style/quality problems we have are already in the codebase (and have been for ages), and, as far as I can see, HoundCI is primarily concerned with GH pull requests, which represent a tiny portion of our code contributions. 

More philosophically, I'll add that doing a "CI" process on code style in the context of Concerto seems extremely odd to me. It's bad enough to suffer under the erratic iron boot of Travis; I don't see much sense in adding another algorithmic overlord in the path of folks trying to contribute.

**Comment by zr2d2** [comment] 2015-03-24 23:03
Well, you philosophical points seem to go against software quality
practices, where contributions (new code) is expected to represent current
quality standards. In that vein, current PRs are what get code reviewed for
quality. Just because something currently is a certain way isn't a good
argument against improving it.

**Comment by augustf** [comment] 2015-03-24 23:07
@zr2d2 While the points philosophical, they do echo my practical objection -- that neither your code nor mine will go through this. To bring another dependency into the project, I think we'd have to have a sense that the benefit provided would be significant. If this were a gem that could evaluate our codebase and provide constructive feedback for improving it, I should be significantly more well-disposed towards it. But a dependency to evaluate the handful of pulls we get hardly seems worth it.

**Comment by acrogenesis** [comment] 2015-03-24 23:31
You could and I would suggest the contributors add the gems houndci uses which are basically rubocop and sass-lint‎. Also it isn't a dependency like Travis that you have to maintain. Practically it's a one time setup.                                                                                                                                                                                                                From: AugustSent: martes, 24 de marzo de 2015 05:07 p.m.To: concerto/concertoReply To: concerto/concertoCc: Adrian RangelSubject: Re: [concerto] Use Houndci (#1191)@zr2d2 While the points philosophical, they do echo my practical objection -- that neither your code nor mine will go through this. To bring another dependency into the project, I think we'd have to have a sense that the benefit provided would be significant. If this were a gem that could evaluate our codebase and provide constructive feedback for improving it, I should be significantly more well-disposed towards it. But a dependency to evaluate the handful of pulls we get hardly seems worth it.

—Reply to this email directly or view it on GitHub.

**Comment by zr2d2** [comment] 2015-03-24 23:41
A) PRs ae how we do/should operate, so i'm dubious of your evaluation of the codebase's nuber of PR's
B) It only makes comments, as @acrogenesis mentions, not a "dependency" or hoop to jump through. Just code reviews, which I find very helpfull

**Comment by augustf** [comment] 2015-03-24 23:50
On (A), while I'm not prepared to concede that having commits through some corporate-esque review process would be a good thing, even if I did, the simple reality is that our code does not primarily come from PR's. But this doesn't have to turn into a development methodology holy war - just an assessment of where our code comes from and where style issues arise from; and the answer is emphatically not PR's.

On (B), when I say dependency, I was referring to adding yet another bunch of gems to the Gemfile. In my opinion, we already have far too many dependencies. After docsplit, I've really come to view any addition of even one more Gem past out present 102 with extreme skepticism.

**Comment by zr2d2** [comment] 2015-03-25 00:13
A) I agree that it's not currently that way, but it is an ideal that we can strive for, and that I think we should  strive for
B) there are no gems to install, it comments through the Github API, as in [here](https://github.com/zr2d2/smartrack/pull/1)

**Comment by augustf** [comment] 2015-03-25 00:17
@zr2d2 Apologies then, I must not be following. Through this discussion, everyone has been speaking about gems (https://github.com/concerto/concerto/issues/1191#issuecomment-85739842). What is the means of installation then (the HoundCI site is extremely short on details of any sort)?

**Comment by zr2d2** [comment] 2015-03-25 00:25
@augustf a repo owner (a member of the owning team) would login [here](https://houndci.com) and activate I think what @acrogenesis was saying is that there are gems that hound uses to perform the analysis that we could use internally if we wanted

**Comment by augustf** [comment] 2015-03-25 00:28
@zr2d2 Well then, while it may not be very useful, there's really no downside I can perceive.

**Comment by zr2d2** [comment] 2015-03-25 00:35
@augustf I don't see how code reviews could be seen as "not be very useful", but ok

**Comment by kench** [comment] 2015-03-25 01:17
It's been a while since we last had a hangout, but I think we should have one and dedicate it to code review/HoundCI/software development practices we might want to use for Concerto.

**Comment by zr2d2** [comment] 2015-03-25 01:18
@kench SGTM


Zach Rowe

**Closed** 2015-08-21 23:12 UTC
Labels: 2.x
