### ISSUE TITLE
Frontend shows black screen

### ISSUE THREAD

**Issue by andrey-sw** [concerto/concerto#1248] opened 2015-09-16 04:14 UTC
Concerto Version: 2.3.0.
ConcertoFrontend via rubygems Gem version: 0.0.8

http://mysite/frontend/1

Google Chrome 45.0.2454.85 m - OK

FireFox 40.0.3 (webobjects is enabled) - Black Screen
in console 1 warn and 1 error
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create 1:215:0
TypeError: this.$ is undefined 1:8948:8

IE11 - Black Screen

**Comment by andrey-sw** [comment] 2015-09-16 07:58
If you open a tab (http://mysite/frontend/1) and make breakpoint the debugger on the line 8948,  refresh, then open a new tab(http://mysite/frontend/1) and wonder - it works
if continue 1 tab - 2 tab - refresh -> black screen

**Comment by mfrederickson** [comment] 2015-10-23 00:06
duplicate of concerto/concerto-frontend#46

**Closed by mfrederickson** 2015-10-23 00:06 UTC
