### ISSUE TITLE
403 Forbidden on new install

### ISSUE THREAD

**Issue by xadacka** [concerto/concerto#1471] opened 2018-01-19 19:26 UTC
Hey,

I've tried installing on both Debian and Ubuntu. On Debian the installer throws a lot of errors and fails, but on Ubuntu it installs correctly with no problems, then gives a 403 forbidden error on the site when you try to access it. I've tried changing permissions and all that but it still just refuses to load. My vhosts are setup correctly, and I've also tried changing the directory for 000-default to the concerto location but that gives me the same 403 error.

Any help would be greatly appreciated!

**Comment by rom650** [comment] 2018-01-22 18:02
Hello,

I have exactly the same problem. We can see in the error.log file of Apache2 that there is a library problem : 
```
PassengerAgent: error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directory
[passenger:error] [pid 14450:tid 139660823271296] *** Passenger could not be initialized because of this error: Unable to start the Phusion Passenger watchdog: it seems to have crashed during startup for an unknown reason, with exit code 127
```

**Comment by carsifreifunk** [comment] 2018-01-23 06:53
This Error we got after update from jessie to stretch. The reason ist to reinstall 2 gem packages. Maybe we have the same error.

# bundle exec gem uninstall rmagick
# bundle exec gem uninstall mysql (if you use mysql or mariaDB)
# bundle install (bundle will install the missing gem packages)

**Comment by zxa** [comment] 2018-02-09 08:24
I had the same issue on Ubuntu 16.04. I solved it by installing Passenger from the Phusion repo, like it is explained here: https://www.phusionpassenger.com/library/install/apache/install/oss/xenial/

There seems to be an issue with the Ubuntu Passenger package, it's not a Concerto problem.

**Comment by mfrederickson** [comment] 2018-03-14 17:23
Well for the Ubuntu install, the `add_repo.sh` script looks based on Debian (stretch) and not Ubuntu (xenial) so that might be why the solution mentioned by @zxa is needed.  I've run into this same Ubuntu/passenger issue with other non-concerto projects.

```
curl -k https://get.concerto-signage.org/add_repo.sh
#!/bin/bash

sudo apt-get install apt-transport-https
wget -O - http://dl.concerto-signage.org/concerto_deb_public.key | sudo apt-key add -
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 561F9B9CAC40B2F7
echo 'deb http://dl.concerto-signage.org/packages/ stretch main\ndeb https://oss-binaries.phusionpassenger.com/apt/passenger stretch main' > /tmp/concerto.list
sudo cp -fr /tmp/concerto.list /etc/apt/sources.list.d/
rm /tmp/concerto.list
sudo apt-get update
```

But the debian install should have gone smoothly... I'll look into that.

**Comment by mfrederickson** [comment] 2018-03-14 19:00
So on a fresh install of Debian 9, I had to install curl and sudo before I ran the `add_repo.sh` script.
I got a message about the passenger signature not being verified.  So I added the key as mentioned in the phusion passenger install directions (from the link above).  After this, I reran the `add_repo.sh` script and it ran cleanly.  Next I ran the `apt-get install concerto-full` command.

I did get the following errors:
```
Run `rake db:migrate` to update your database then try again.
dpkg: error processing package concerto-full (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for systemd (232-25+deb9u2) ...
Errors were encountered while processing:
 concerto-full
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

However, it looks like these might have been caused by something running before the migrations finished occurring.

Running `apt-get install concerto-full` again seems to hang on the second run of bundler, and then gives a timeout expired message.  So I removed the migration_tempfile from /usr/share/concerto/tmp and tried again.  It gave me the same errors as above.  I believe this is mentioned here  #concerto-debian/67.

After removing the migration_tempfile again, changing into the /usr/share/concerto directory and running the following:  **THIS IS DESTRUCTIVE AND WILL WIPE OUT YOUR CONCERTO DATABASE**-- which is not a problem for a new install, which is what we are working on.
```
RAILS_ENV=production bundle exec rake db:drop
RAILS_ENV=production bundle exec rake db:create
RAILS_ENV=production bundle exec rake db:migrate
RAILS_ENV=production bundle exec rake db:seed
```
I was able to get the migrations applied.  Then I installed concerto-full again and it compiled the assets and enabled the site, and gave me the message mentioned here #concerto-debian/68.

I then disabled the apache 000-default site, reloaded apache2 and everything works fine.
```
a2dissite 000-default
systemctl reload apache2
```
So, it does indeed look like there is some work to be done on the installation for debian, but thankfully  @augustf has already identified them and created issues for them.  Hopefully we can get these resolved by the next release.

**Closed** 2018-03-14 19:11 UTC
Labels: 2.x
